### PR TITLE
[ RPP-84 ]-README-file

### PR DESCRIPTION
**Pull request by Fortesacena**

### CODE REVIEW

**Review by Vijola-Neziri — COMMENTED** [review]
perfect

**Comment by Vijola-Neziri** [comment]
perfect

**Review by Vijola-Neziri — COMMENTED** [review]
perfect

**Review by ylljetakicaj — APPROVED** [review]

**Comment by Vijola-Neziri** [comment]
perfe

**Review by Vijola-Neziri — APPROVED** [review]

**Review by erza-b — APPROVED** [review]

**Review by SuhejlaHoxha — APPROVED** [review]

**Pull request merged**
